"""add users deactivated_at

Revision ID: 8cd711ec9aec
Revises: b86e0f8e3603
Create Date: 2026-10-07 14:08:50.285242

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '8cd711ec9aec'
down_revision: str | None = 'b86e0f8e3603'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###
